### ISSUE TITLE
Innlogging på Safari

### ISSUE THREAD

**Issue by LilleAila** [Kaffe-diem/kaffediem#15]
Gjelder for safari på både IOS og MacOS. Trykker login-knappen, men ingenting skjer.

> Jeg testet lokalt at funksjonalitet er OK i Firefox og Safari. Jeg er ikke kjent med spesifikt hvordan implentasjonen bør se ut i henhold til samhold mellom PB, Svelte, og OAauth, @LilleAila var dette basert på [artikkelen du delte](https://dev.to/mpiorowski/oauth2-is-so-complicated-or-90-lines-of-code-with-svelte-532)? Det ser delvis slik ut.
> 
> Firefox er OK, Safari på Mac fungerer ikke, det kan være relevant å se på diskusjoner fra (https://github.com/pocketbase/pocketbase/discussions/2429#discussioncomment-5943061)
> 
> Dette virker som et kjent problem.
> 
> Observasjon: Når pop-up vindu åpnes og en bruker er valgt, vil pop-upen lukkes.
> Forventet resultat: Jeg er logget inn på selektert bruker.
> Gitt resultat: Jeg er ikke logget inn på selektert bruker.
> 
> Jeg tror vi må tilbake å debugge dette eksakte problemet, men jeg velger å godkjenne PR ettersom dette er et etablert problem rundt PB og G OAuth. Lager issue om saken.

@kluvin  https://github.com/Kaffe-diem/frontend/pull/8#pullrequestreview-2379757255

**Comment by kluvin** [comment]
PB forfatter bruker PB i sitt eget prosjekt, hvor det fins en løsning.

https://github.com/presentator/presentator/blob/09609c49c67275bf42ec7769d59a9d3d72f63645/ui/src/components/base/SocialAuth.svelte#L9
https://github.com/presentator/presentator/blob/master/ui/src/pb.js
https://github.com/pocketbase/pocketbase/discussions/2429#discussioncomment-10231074

Vi kan prøve å lære litt fra dette prosjektet.

**Comment by kluvin** [comment]
basert på https://github.com/pocketbase/pocketbase/discussions/3478

Og [kaffe-diem](https://kaffe-diem.web.app/) fungerer logg-in når cookie er secure. Det vil si at `secure`må være `false` på localhost, for Safari har ikke unntak som andre nettlesere for dette.

Det er fint mulig å ignorere dette problemet da. Derimot så virker ikke helt log-in fra mobil på Safari. Det virker som det har noe med dropdown valget å gjøre, for "Logg inn for å se menyen" fungerer som vanlig.

Forslag: Vi bare flytter "logg ut/inn" fra dropdown menyen, og plasserer den ved siden av.

**Comment by LilleAila** [comment]
> Det er fint mulig å ignorere dette problemet da. Derimot så virker ikke helt log-in fra mobil på Safari. Det virker som det har noe med dropdown valget å gjøre, for "Logg inn for å se menyen" fungerer som vanlig.

Jeg husker noe lignende skjedde mens jeg lagde nav-componenten, jeg tror det kan fikses med å sette en `tabindex="0"` på button i AuthButton.svelte

**Comment by kluvin** [comment]
Vi kan prøve før vi flytter den.

Dette høres dog ut som en merkelig løsning, tabindex bør ikke påvirke interaktivitet via cursor.

**Comment by LilleAila** [comment]
> Vi kan prøve før vi flytter den.
> 
> Dette høres dog ut som en merkelig løsning, tabindex bør ikke påvirke interaktivitet via cursor.

Safari er merkelig ¯\_(ツ)_/¯, det fikset samme problem for <a>. Kan også være noe med display-property i css

**Comment by LilleAila** [comment]
Dette ser ut til å bare ha begynt å virke av seg selv, i hvertfall i [4225f1f](https://github.com/Kaffe-diem/kaffediem/pull/68/commits/4225f1f0b301f819aea853f63c0dfb6a87e878e0), når jeg trykket gjennom firebase sin preview.

**Comment by kluvin** [comment]
Oki, lukker når den er merget i såfall. Testet i prod tidligere i dag
