### ISSUE TITLE
API mappe?

### ISSUE THREAD

**Issue by CarlAugust** [Kaffe-diem/kaffediem#24]
Burde vi lage en mappe for api, aka funksjoner for å hente og sette in i databasen, eller er det bedre å skrive koden i page routen med en +page.server.ts fil og i +page.svelte filen?

**Comment by kluvin** [comment]
jeg holder på med noe slikt her:

https://github.com/Kaffe-diem/frontend/pull/9

**Comment by IldenH** [comment]
#57 har gjort dette for orders. Vi kan kanskje gjøre det for andre ting også som displayMessages, men lukker for nå.
