### ISSUE TITLE
Oppgradere til Svelte 5 før vi har for mye å gjøre?

### ISSUE THREAD

**Issue by kluvin** [Kaffe-diem/kaffediem#51]
@LilleAila Valgte du spesifikt Svelte 4 da du satte opp frontenden første gang? Hva var grunnlaget?

**Comment by LilleAila** [comment]
Jeg valgte ikke spesifikt svelte 4. Jeg brukte bare `create-svelte` og fulgte dokumentasjonen til sveltekit.

**Comment by kluvin** [comment]
Ah, svelte 5 ble lansert offisielt en uke etter første commit.

Jeg er veldig ivrig på å gå over til Svelte 5 da. Spesielt med tanke på at vi får HMR.

**Comment by IldenH** [comment]
Lukket av #56.
